# Generated by Django 5.0.6 on 2024-08-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
        migrations.AlterModelTable(
            name='abonoanticipo',
            table='AbonoAnticipo',
        ),
        migrations.AlterModelTable(
            name='abonocredito',
            table='AbonoCredito',
        ),
        migrations.AlterModelTable(
            name='anticipo',
            table='Anticipo',
        ),
        migrations.AlterModelTable(
            name='articulo',
            table='Articulo',
        ),
        migrations.AlterModelTable(
            name='caja',
            table='Caja',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='cortecaja',
            table='CorteCaja',
        ),
        migrations.AlterModelTable(
            name='credito',
            table='Credito',
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='DetalleVenta',
        ),
        migrations.AlterModelTable(
            name='listaprecio',
            table='ListaPrecio',
        ),
        migrations.AlterModelTable(
            name='listapreciocliente',
            table='ListaPrecioCliente',
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='MetodoPago',
        ),
        migrations.AlterModelTable(
            name='metodopagoventa',
            table='MetodoPagoVenta',
        ),
        migrations.AlterModelTable(
            name='movimientocaja',
            table='MovimientoCaja',
        ),
        migrations.AlterModelTable(
            name='precio',
            table='Precio',
        ),
        migrations.AlterModelTable(
            name='saldometodopago',
            table='SaldoMetodoPago',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='Venta',
        ),
    ]
