# Generated by Django 5.0.6 on 2024-08-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_contraseña_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
