# Generated by Django 5.0.6 on 2024-11-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticipo',
            name='fecha',
        ),
    ]
