# Generated by Django 5.1.7 on 2025-03-31 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_anticipo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='deuda_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credito',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
